### ISSUE TITLE
How to create interface files to upload to the server?

### ISSUE THREAD

**Issue by LeRoYGo** [blockworks-foundation/mango-ui-v3#106]
Hi. Can you tell me how to create files to upload to the server. For example, in the repository https://github.com/project-serum/serum-dex-ui just write yarn build. It will automatically create a "build" folder with all the necessary files to upload to the server.

**Comment by riordanp** [comment]
Hey @LeRoYGo,

I thought you could run `yarn build && yarn next export` which would create an `out` directory, but this doesn't seem to support i18n https://github.com/vercel/next.js/discussions/18957

You might be able to apply one of the workarounds in the linked thread
