### ISSUE TITLE
How do I change the default theme?

### ISSUE THREAD

**Issue by LeRoYGo** [blockworks-foundation/mango-ui-v3#108]
How do I make the default design theme "Dark" instead of "Mango"? In which file should I change the code?And is it also possible to remove the Mango theme from the app?

**Comment by riordanp** [comment]
You should be able to change this line to set the default: https://github.com/blockworks-foundation/mango-ui-v3/blob/main/pages/_app.tsx#L90

You might be able to remove the mango theme from here: https://github.com/blockworks-foundation/mango-ui-v3/blob/main/tailwind.config.js 
and here:
https://github.com/blockworks-foundation/mango-ui-v3/blob/main/components/ThemeSwitch.tsx

but I have not tried this myself

**Comment by LeRoYGo** [comment]
Thank you for your help. Can you also tell me how to make the default RPC Endpoint "Project Serum" as Triton does not work.

**Comment by riordanp** [comment]
I believe the first item in this list is the default https://github.com/blockworks-foundation/mango-ui-v3/blob/main/components/SettingsModal.tsx#L14

Should just be able to swap the Serum and Triton items

**Comment by LeRoYGo** [comment]
The solution is simple. Thank you.

**Comment by riordanp** [comment]
For future reference, default RPC endpoint needs to be changed here too: https://github.com/blockworks-foundation/mango-ui-v3/blob/main/stores/useMangoStore.tsx#L40
