### ISSUE TITLE
New Account Page Issues

### ISSUE THREAD

**Issue by dafyddd** [blockworks-foundation/mango-ui-v3#147]
I really like the new Account page deployed in https://alpha.mango.markets/account

I'm going to use this Issue to list all minor bugs

1. When you hit Claim Rewards in the top right, it doesn't update the value after tx is successful
2. It's a bit confusing that this says pnl (24 hours) but is actually showing total lifetime pnl. Also pnl on the left is showing total pnl including spot. Maybe naming will help here?
![image](https://user-images.githubusercontent.com/17482744/152385045-44fde987-46aa-416b-b838-d7335ca491a4.png)

**Comment by saml33** [comment]
@dafyddd @tjshipe @nicholasgodfreyclarke – Have updated. Not 100% confident on the pnl values over the different timeframes. Let me know if it looks off for you

**Comment by dafyddd** [comment]
Thanks @saml33 I'll take a look if/when it's pushed to alpha.mango

1. I'd prefer if the MangoAccount address at top left would not take you to explorer but just let you copy it. What do you think? Do you usually want it to open a new explorer tab? I find myself never wanting to do that. 

2. I think there should be commas in all the large numbers. Makes it much easier to read. For example the perp positions table should probably display positions with commas.

**Comment by saml33** [comment]
I haven't had the need to do either really. Will add copy back. Did I see you can send tokens directly to your mango account now? Might have been that it's easier to recover if someone does... I guess encouraging copying might make it more likely for that to happen

Yeah agree

I'll push the new changes to alpha @dafyddd

**Comment by saml33** [comment]
I've pushed these updates to alpha. Wasn't sure how we should handle precision in the balances table. Have left it at the token decimals but that seems unnecessary. Guess it's kind of tricky as we don't want balances to show as 0.0000 or whatever. We have those precision objects in utils but they don't seem right either?

@dafyddd @tjshipe
