### ISSUE TITLE
Chart is showing Error while run Code locally ..

### ISSUE THREAD

**Issue by itxnaeem007** [blockworks-foundation/mango-ui-v3#25]
While fork the code and run locally , the chart is showing that error .
![Screenshot from 2021-09-07 14-06-30](https://user-images.githubusercontent.com/89545777/132317628-c59b3851-8899-4ed6-a90a-895e78b23aa6.png)

**Comment by itxnaeem007** [comment]
Kindly Guideline me on that issue ..

**Comment by Naeem-source** [comment]
@mschneider @bonipart @tjshipe @riordanp   Kindly Ans this

**Comment by bonipart** [comment]
@itxnaeem007

Instead of `yarn && yarn dev`, try `yarn build && yarn start`

Credit goes to @swappadoodledooooo for mentioning this fix...

**Comment by tjshipe** [comment]
Fixed. Thanks!
