### ISSUE TITLE
Market price not displayed in the browser tab title anymore 

### ISSUE THREAD

**Issue by rtviii** [blockworks-foundation/mango-ui-v3#84]
The price fetching into the tab title doesn't seem to work anymore.. It's a super convenient feature! 
I gather the issue is here but i'm not super familiar with how the state is represented... could someone take a look ? :)
@
https://github.com/blockworks-foundation/mango-ui-v3/blob/e423dfee6d47fa362b1d6c04f0169562feeccbb7/pages/_app.tsx#L25-L32

**Comment by tjshipe** [comment]
Fixed. Thanks!
