### ISSUE TITLE
Why show the Mango address so prominently?

### ISSUE THREAD

**Issue by tredondo** [blockworks-foundation/mango-ui-v3#96]
![image](https://user-images.githubusercontent.com/10043369/143575109-866e8b1b-7314-4ac7-812c-6df173d80748.png)

This is an [attractive nuisance](https://en.wikipedia.org/wiki/Attractive_nuisance_doctrine). New users might think that's their account address and would transfer SOL there, and lose their money.

That address also shows at https://trade.mango.markets/account. If there's a good reason to show it, a warning not to send money there might be useful.

**Comment by tjshipe** [comment]
Warning added to account page
