### ISSUE TITLE
UI crashes on click Repay button

### ISSUE THREAD

**Issue by gregkonush** [blockworks-foundation/mango-ui-v3#97]
![image](https://user-images.githubusercontent.com/12027037/143792931-bf806c72-5562-4453-8f89-6bbd4a513e83.png)

Console Errors:
![image](https://user-images.githubusercontent.com/12027037/143792945-08de831d-88a7-4233-abec-893693ff344a.png)

**Comment by tjshipe** [comment]
Fixed. Thanks
